CREATE TABLE  "AUTEUR" 
   (	"ID_AUTEUR" NUMBER(*,0) NOT NULL ENABLE, 
	"NOM_AUTEUR" VARCHAR2(100) NOT NULL ENABLE, 
	"PRENOM_AUTEUR" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "AUTEUR_PK" PRIMARY KEY ("ID_AUTEUR") ENABLE
   )
/


*-*-*-*-

CREATE TABLE  "DDE_DOCUMENT" 
   (	"TITRE" VARCHAR2(100) NOT NULL ENABLE, 
	"QUANTITE" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "DDE_DOCUMENT_PK" PRIMARY KEY ("TITRE") ENABLE
   )
/


        
*-*-*-*-*-*-*-*-*

CREATE TABLE  "DEMANDE" 
   (	"ID_DEMANDE" NUMBER(*,0) NOT NULL ENABLE, 
	"LA_DATE" DATE NOT NULL ENABLE, 
	"URGENCE" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "DEMANDE_PK" PRIMARY KEY ("ID_DEMANDE") ENABLE
   )
/


*-*-*-*-*-*-*-*-

CREATE TABLE  "DEMANDER_NV" 
   (	"REFERENCE" VARCHAR2(100) NOT NULL ENABLE, 
	"ID_DEMANDE" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_DES" NUMBER(*,0) NOT NULL ENABLE, 
	"QUANTITE" NUMBER(*,0) NOT NULL ENABLE, 
	"DECISION" VARCHAR2(100) DEFAULT 'pas encore' NOT NULL ENABLE, 
	 CONSTRAINT "DDE_NV_PK" PRIMARY KEY ("REFERENCE", "ID_DEMANDE", "ID_DES") ENABLE, 
	 CONSTRAINT "DEMANDER_NV_DEPT_FK" FOREIGN KEY ("REFERENCE")
	  REFERENCES  "DEPARTEMENT" ("REFERENCE") ENABLE, 
	 CONSTRAINT "DEMANDER_NV_DDE_FK" FOREIGN KEY ("ID_DEMANDE")
	  REFERENCES  "DEMANDE" ("ID_DEMANDE") ENABLE, 
	 CONSTRAINT "DEMANDER_NV_DESGN_FK" FOREIGN KEY ("ID_DES")
	  REFERENCES  "DESIGNATION" ("ID_DES") ENABLE
   )
/

*-*-*-*-*-*-*-*-*-*

CREATE TABLE  "DEPARTEMENT" 
   (	"REFERENCE" VARCHAR2(100) NOT NULL ENABLE, 
	"DESIGNATION" VARCHAR2(100) NOT NULL ENABLE, 
	"ID_STOCK" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "DEPARTEMENT_PK" PRIMARY KEY ("REFERENCE") ENABLE
   )
/

*-*-*-*-*-*-*-*-*- LAST

CREATE TABLE  "DEPLACER_MATERIEL" 
   (	"REFERENCE" VARCHAR2(100) NOT NULL ENABLE, 
	"ID_MAT" NUMBER(*,0) NOT NULL ENABLE, 
	"LA_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "DEPLACER_MATERIEL_PK" PRIMARY KEY ("REFERENCE", "ID_MAT", "LA_DATE") ENABLE, 
	 CONSTRAINT "DEPLACER_MAT__DEPT_FK" FOREIGN KEY ("REFERENCE")
	  REFERENCES  "DEPARTEMENT" ("REFERENCE") ENABLE, 
	 CONSTRAINT "DEPLACER_MAT__MAT_FK" FOREIGN KEY ("ID_MAT")
	  REFERENCES  "MATERIEL" ("ID_MAT") ENABLE
   )
/


*-*-*-*-*-*-*-*

CREATE TABLE  "DESIGNATION" 
   (	"ID_DES" NUMBER(*,0) NOT NULL ENABLE, 
	"DESIGNATION" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "DESIGNATION_PK" PRIMARY KEY ("ID_DES") ENABLE
   )
/

*-*-*-*-*-*-*-

CREATE TABLE  "DOC_PRIS" 
   (	"ID_PRENDRE_DOC" NUMBER(*,0) NOT NULL ENABLE, 
	"ETAT_PRENDRE_DOC" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "DOC_PRIS_PK" PRIMARY KEY ("ID_PRENDRE_DOC") ENABLE
   )
/

CREATE TABLE  "DOC_PRIS" 
 (	"ID_PRENDRE_DOC" NUMBER(*,0) NOT NULL ENABLE, 
	"ETAT_PRENDRE_DOC" VARCHAR2(100) NOT NULL ENABLE, 
	"DATE_EMPRUNT" TIMESTAMP (6), 
	"DATE_RETOUR" TIMESTAMP (6), 
	 CONSTRAINT "DOC_PRIS_PK" PRIMARY KEY ("ID_PRENDRE_DOC") ENABLE
   )
/




*-*-*-*-*-*-*-*-*-* 

CREATE TABLE  "DOCUMENT" 
   (	"NUM_SERIE" NUMBER(*,0) NOT NULL ENABLE, 
	"ISBN" VARCHAR2(100) NOT NULL ENABLE, 
	"TITRE" VARCHAR2(100) NOT NULL ENABLE, 
	"NUM_PAGE" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_AUTEUR" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_DOMAINE" NUMBER(*,0) NOT NULL ENABLE, 
	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "DOCUMENT_PK" PRIMARY KEY ("NUM_SERIE") ENABLE, 
	 CONSTRAINT "DOCUMENT__AUTEUR_FK" FOREIGN KEY ("ID_AUTEUR")
	  REFERENCES  "AUTEUR" ("ID_AUTEUR") ENABLE, 
	 CONSTRAINT "DOCUMENT__DOMAINE0_FK" FOREIGN KEY ("ID_DOMAINE")
	  REFERENCES  "DOMAINE" ("ID_DOMAINE") ENABLE, 
	 CONSTRAINT "DOCUMENT__DOC_PRIS1_FK" FOREIGN KEY ("ID")
	  REFERENCES  "DOC_PRIS" ("ID_PRENDRE_DOC") ENABLE
   )
/

*-*-*-*-*-*-*-*-*-*

CREATE TABLE  "DOMAINE" 
   (	"ID_DOMAINE" NUMBER(*,0) NOT NULL ENABLE, 
	"LIBELLE" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "DOMAINE_PK" PRIMARY KEY ("ID_DOMAINE") ENABLE
   )
/

*-*-*-*-*-* 

CREATE TABLE  "EMPRUNTER" 
   (	"NUM_SERIE" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_USER" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "EMPRUNTER_PK" PRIMARY KEY ("NUM_SERIE", "ID_USER") ENABLE, 
	 CONSTRAINT "EMPRUNTER__DOCUMENT_FK" FOREIGN KEY ("NUM_SERIE")
	  REFERENCES  "DOCUMENT" ("NUM_SERIE") ENABLE, 
	 CONSTRAINT "EMPRUNTER__UTILISATEUR0_FK" FOREIGN KEY ("ID_USER")
	  REFERENCES  "UTILISATEUR" ("ID_USER") ENABLE
   )
/


*-*-*-*-*-*-*

CREATE TABLE  "ETAT" 
   (	"ID_ETAT" NUMBER(*,0) NOT NULL ENABLE, 
	"ETAT_MAT" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "ETAT_PK" PRIMARY KEY ("ID_ETAT") ENABLE
   )
/

*-*-*-*-*-*-*-*-* 

CREATE TABLE  "ETRE_CHEF" 
   (	"ID_USER" NUMBER(*,0) NOT NULL ENABLE, 
	"REFERENCE" VARCHAR2(100) NOT NULL ENABLE, 
	"DATE_DEBUT" DATE NOT NULL ENABLE, 
	"DATE_FIN" DATE, 
	 CONSTRAINT "DEMANDER_NV_PK" PRIMARY KEY ("ID_USER", "REFERENCE") ENABLE, 
	 CONSTRAINT "ETRE_CHEF__CHEF_DEPT_FK" FOREIGN KEY ("ID_USER")
	  REFERENCES  "UTILISATEUR" ("ID_USER") ENABLE, 
	 CONSTRAINT "ETRE_CHEF__DEPARTEMENT_FK" FOREIGN KEY ("REFERENCE")
	  REFERENCES  "DEPARTEMENT" ("REFERENCE") ENABLE
   )
/

*-*-*-*-*-*-*-*-*-*

CREATE TABLE  "FONCTION" 
   (	"ID_FCT" NUMBER(*,0) NOT NULL ENABLE, 
	"NOM_FCT" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "FONCTION_PK" PRIMARY KEY ("ID_FCT") ENABLE
   )
/

*-*-*-*-*-*-*-*-*-*-*-*

CREATE TABLE  "MATERIEL" 
   (	"ID_MAT" NUMBER(*,0) NOT NULL ENABLE, 
	"REF_MAT" VARCHAR2(100) NOT NULL ENABLE, 
	"PRIX_HT" FLOAT(126) NOT NULL ENABLE, 
	"TVA" FLOAT(126) NOT NULL ENABLE, 
	"ID_DES" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_ETAT" NUMBER(*,0) NOT NULL ENABLE, 
	"IMAGE" BLOB, 
	"CURRENT_DEPT" VARCHAR2(100) DEFAULT 'AD1252', 
	 CONSTRAINT "MATERIEL_PK" PRIMARY KEY ("ID_MAT") ENABLE, 
	 CONSTRAINT "MATERIEL__DESIGNATION_FK" FOREIGN KEY ("ID_DES")
	  REFERENCES  "DESIGNATION" ("ID_DES") ENABLE, 
	 CONSTRAINT "MATERIEL__ETAT0_FK" FOREIGN KEY ("ID_ETAT")
	  REFERENCES  "ETAT" ("ID_ETAT") ENABLE
   )
/


*-*-*-*-*-*-*-*-*-*


CREATE TABLE  "UTILISATEUR" 
   (	"ID_USER" NUMBER(*,0) NOT NULL ENABLE, 
	"NOM" VARCHAR2(50) NOT NULL ENABLE, 
	"PRENOM" VARCHAR2(100) NOT NULL ENABLE, 
	"CIN" VARCHAR2(100), 
	"CNE" VARCHAR2(100), 
	"NUM_SOMME" VARCHAR2(100), 
	"LOGIN" VARCHAR2(100) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(100) NOT NULL ENABLE, 
	"GRADE" NUMBER(*,0) NOT NULL ENABLE, 
	"RESP_DEPT" VARCHAR2(100), 
	 CONSTRAINT "UTILISATEUR_PK" PRIMARY KEY ("ID_USER") ENABLE, 
	 CONSTRAINT "UTILISATEUR__FONCTION_FK" FOREIGN KEY ("GRADE")
	  REFERENCES  "FONCTION" ("ID_FCT") ENABLE
   )
/


-*-*-*-*-*-*-*-*-*-*-


manque d'une table association entre auteur et document (etre auteur)
emprunter : date_emprunt ---- date_depot de type timestamp
dde_document : satisfaire number(10);

