CREATE OR REPLACE VIEW vue_utilisateur AS 
SELECT U.id_user, U.Nom, U.Prenom, U.CIN, U.CNE, U.Num_somme, F.NOM_FCT, D.Designation
FROM UTILISATEUR U
INNER JOIN FONCTION F ON F.ID_FCT=U.Grade 
INNER JOIN DEPARTEMENT D ON F.ID_FCT=U.Grade AND D.Reference=U.Resp_dept; 



CREATE OR REPLACE VIEW vue_document AS 
SELECT Dc.Num_Serie, Dc.isbn, Dc.titre, Dc.num_page, A.NOM_AUTEUR, Dm.LIBELLE, Dp.ETAT_PRENDRE_DOC
FROM DOCUMENT Dc
INNER JOIN AUTEUR A ON Dc.id_auteur=A.ID_AUTEUR 
INNER JOIN DOMAINE Dm ON Dc.id_domaine=Dm.ID_DOMAINE AND Dc.id_auteur=A.ID_AUTEUR
INNER JOIN DOC_PRIS Dp ON Dp.ID_PRENDRE_DOC=Dc.Id AND Dc.id_domaine=Dm.ID_DOMAINE AND Dc.id_auteur=A.ID_AUTEUR;



CREATE OR REPLACE VIEW vue_historique AS
SELECT U.id_user, U.Nom, Doc.Num_Serie, Doc.titre, E.ID_USER USER_ID, E.NUM_SERIE SERIE_NUM, E.DATE_EMPRUNT, E.DATE_DEPOT
FROM UTILISATEUR U
INNER JOIN EMPRUNTER E ON U.id_user=E.ID_USER
INNER JOIN DOCUMENT Doc ON E.NUM_SERIE=Doc.Num_Serie AND U.id_user=E.ID_USER;